spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.215.149:3306/zooflix?serverTimezone=UTC&characterEncoding=UTF-8
    username: malangcow
    password: malang203
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8089

jwt:
  secret: malangmalangmalangmalangmalangmalangcowcowcowcowzooflixmalangcowzoozooflextflextflixflixzooflixmalang

security:
  db:
    rsa:
      public-encode-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAoF7C07BQmpBB4c0Q/3wKzVLmw/afxO+budej1JiAmzYQcr2FUw4H/vaI2e/N+zKAAOZTOLX+JO+71eRQNKI07GzpxlGvRhHCLGfnuvrm0PJ9BIGG7zTGaUIT5gWW8QxdsZNLhYJZ/z/c3J2aNUcUjUQWlGdqA4Zd2Qcx6gmqBoCc2S/aIKD0mfIneECz+vV4P67tuB3a2f5Nn8XK/VEYpoCF4t+8EkUCqE2ayFSX2fNeZW2NvH6Hqaskha1ehg/QQEnyLJ6Fy9MiFQXOXG30Abjh0zvi8FoiHQ2BSQVewSxlGxiLfOOp1y8qMXnYquP0jI76EZ1E5CfqSThKoe1I2QIDAQAB
      private-decode-key: MIIEugIBADANBgkqhkiG9w0BAQEFAASCBKQwggSgAgEAAoIBAQCgXsLTsFCakEHhzRD/fArNUubD9p/E75u516PUmICbNhByvYVTDgf+9ojZ7837MoAA5lM4tf4k77vV5FA0ojTsbOnGUa9GEcIsZ+e6+ubQ8n0EgYbvNMZpQhPmBZbxDF2xk0uFgln/P9zcnZo1RxSNRBaUZ2oDhl3ZBzHqCaoGgJzZL9ogoPSZ8id4QLP69Xg/ru24HdrZ/k2fxcr9URimgIXi37wSRQKoTZrIVJfZ815lbY28foepqySFrV6GD9BASfIsnoXL0yIVBc5cbfQBuOHTO+LwWiIdDYFJBV7BLGUbGIt846nXLyoxediq4/SMjvoRnUTkJ+pJOEqh7UjZAgMBAAECgf8kT6SHrjYAwY9EAmJ0B8mpZI8OSS/bK79ogjuue976naYPWKHIpzKDB9QDBoEFtA1UCEF2zpgcw/ARtulwQmajUWsKH02HSNjTG1nrmmLXk9qolf2LAPMQKdF3HPX2CFNpzwlkzZXkP48jjN3zOtzJjIbicdoOthS2qIlwqINXaMno0lkBXBBEXdTHUvnX08bDNBGlg8cRByb85eAMko8tpLG4K8LWjmUy4hiONhN3z7pd+Jr3u4mbOmH5auI5gIEIShNYVBFKhVrm+xGYPV4auwAnmyZpLmoXEFV0tiKvDGLmV5QSkfJWbAYRg2d10M/bM+89ziqX8lBA1HSfFRECgYEAtyLS9ZDhyFtpKj7Jm78RMzQqsCHesx9B77NrDpqXDAZ9/zb5ibf3Q32G9W0cDOeDU9ZAXtpCtTUZGE7V+lCGRG/AZDqmFv4QA9nQXbzHC1JJ2JOp7Kmd+J15pgpGA3aSd+cmQYstItsk6zcdb3d/8zpYZgx2oSjdWpKKEr2WxykCgYEA4C0jG+wMF2gmUkSzxs3L5W4nIFTKoE4QYHUG/ZTZbOLg4tIqsGFsEWkTAxk3J3wTmWn8EpY4ootK8iopPNaVxw4JWHPfp6H9RWmfg6/VBSysQ1v80fR9Rg2pI0v+p4B30U0sQLax87QR0B0gMVIPdVfqZRGpkGDOeEEiQDb/GjECgYAJUQY2Y+Z4kN3qvkL3X2L6nd7GExMHPcHW9eOuXILuo63pO9y5+tfjYRFqjuBsb6Kosy+XI7ddDJR4Php4n3wVIzJAZxNn/AjIiV4mRqJBmzASioCMf5x/t1Mm9ULWjkOpQeMaVoA3U7qvFKC0uPmTYBZ7Kosma7PHFclcZrSy8QKBgBTvIiAxYs+swidckw01mpzKNI0oXeOqZo0bYJO9mrA4X5fO2H2wG09k6ImZiTT+uTXSV9/Ed3V2XIFQvpkX0NTN0sGX0ILu9Z/NxT+e492f1lZT+MACfNBV5j2NkzJBJO8+ras9ZFDFuAQfNCpm51ql4xWdGKCK6b0BGBm3CQuBAoGAThbSHEs348QdorfUGQxC2w16+fvC1qHdsClpE87tk8HY3Wbuz5qfuBNJ0Xr1UMU/R/PpibB5kOTStnWXGLYVzcrmbtQ2tSdbpIY3aEyrovjZiv3AGCmLZMhvYpgqImxqx3TI0y6itiIbtj7O5Lz8hD+cB1lNVQhXJM1cIexxPM4=
    aes:
      private-key: MALANGMALANGZOOFLIXA203FERYAKGOV
  api:
    rsa:
      public-encode-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA01p3IADOMEftfxltnPWF476vMUrAgiadvT2seHff1tkHWxV+TgMrMvRKcUkjRCNKV+UgqKiBVYUd+mkIVno8GsURBmf6nmjcd6aYm/xGu6peHc7iE6wlIoBa8maglinAiNglPSyeJlELXDnoqN4AnT6OWmKlkbAiGH730a+qjsv73jVubZziL8FHWX8MlP6F7SknVmaa7fzU5rof7cHaFDu95s9h9fppjoqOBk1lyqEfikTUofBexGqtFPR/+6cA0KcBTyJnlvCP3XTWkbfqdDMhgLmfGnMYCXqGzjWehUEeeWwGekbqc+nZRwWSDtzuGB0wwmyMStjCpt6JLNdftQIDAQAB
      private-decode-key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDTWncgAM4wR+1/GW2c9YXjvq8xSsCCJp29Pax4d9/W2QdbFX5OAysy9EpxSSNEI0pX5SCoqIFVhR36aQhWejwaxREGZ/qeaNx3ppib/Ea7ql4dzuITrCUigFryZqCWKcCI2CU9LJ4mUQtcOeio3gCdPo5aYqWRsCIYfvfRr6qOy/veNW5tnOIvwUdZfwyU/oXtKSdWZprt/NTmuh/twdoUO73mz2H1+mmOio4GTWXKoR+KRNSh8F7Eaq0U9H/7pwDQpwFPImeW8I/ddNaRt+p0MyGAuZ8acxgJeobONZ6FQR55bAZ6Rupz6dlHBZIO3O4YHTDCbIxK2MKm3oks11+1AgMBAAECggEAALSY2LG//m/DBm1UjRVRttakWY8FEPolhSPvTzChPeOYD3EFLKf8jS09EV8736aZgS0Z3I5BbkJlPPh8R2Odjz5QpfuTXdN+RuT2tfCT4Nz69vEBlqy4rAKPKyd2CkJF6v8Dss5TEdAr8EkeMnAZQu0aRwl0wYV7u6ay14+VS2g315/xvK+R3krlRf89/0NB5wGVRMt8kC10qT1MxQ0wgWENNypVbUHv2uIzLbXeulA+PpsBKwWGeCJPsCrXPoLClCb/bIy8IqtkqKdBS4hfioNfJRaCJ6yQiuCzkQinj2tGkNErcR8De3lVDqN+SN05k57efXv1Hi1ZV4pTALzTMQKBgQDjX8SZhyZXbCorV347GThzCvQpceZvgVYMoLrWK5yo7QBajnoi7mpnUaI+WjMR9d8g0zKax1yYn0uALjTiAyiyUfC69vvnCZ35/oOAbwjmeuXy2odVY83v6uz/DgeuQvUA9KNu8rmW6Onu7pXY8fYeYEOOccEfdidTAGE8r9B5ZQKBgQDt9losOhJrU8/KgYvL6zz1BoC9FaV+B7E2DUi2ee2JbfexgBCtON+/vd3/nNUPcnzhV7GmXgIVibsID/eaDGIdcgq9Ep/+wx9LNe/vGywmVnD7ygDaB7kXN7iafheX0PjAFHQHPnYXlJQ2crVx5GyV+EeC45oLPzpWU39L1LUQEQKBgAEBkXskb/T/E4ixkGtuhyNrLv1n9Z8UsW7I30rHUqAkvFWqP7wb1fizEca423T+44ffp1+r9iruuYTNr4o4fVucpTYOlbrF/h73E1nkI+PxM0dJ1EN6d5TSM05Fn58TyMXCT17UUCHs0ewuvhcBqxcjUek1c6dR/IaPf96m4INJAoGBAIp3elsX45XubBAjN6yOEqdlhE4CpYzjfvu72R7Nbio1AheYNJwHZzNUkTRnFxdpAD/D3oy3UTElNt7nI6XRJNqLfLIuf0koUzJZjWcuAY/BZvcswTgdnFdlRhcn3iSqJcTnYejBMMhh3aidMPW3/HN7yGjidcWrog+PgJgoir9xAoGATeTvkGZF94BHVHipI1UpML6acjyJQWvPTkdx+YJSCmTEMK2lULU0yMGHxD+7293L66+lIsiVDoGaGAI7w6i1SRP1BRymks7L1HaUkgXsuL0CsNt5l3hSLuV1L8x+n8amtAJvl8GbWWaHLYslnOCZQH/IsIwjFhZY7J85Wnbvog0=

python:
  endpoint:
    news:
      crawling: http://127.0.0.1:8000/radio/crawling/translation/endpoint
      summary: http://127.0.0.1:8000/radio/summary/endpoint
      tts: http://127.0.0.1:8000/radio/tts/endpoint
  path:
    news: C:\projects\myapi\News.py
    end-price: C:\projects\myapi\EndPrice.py
  news:
    url: https://www.cnbc.com/world-markets/
  ppg:
    url: https://naveropenapi.apigw.ntruss.com/nmt/v1/translation
    clientId: qag4d44o5y
    clientSecret: eYaYbTl9z0UJ4lBqWrut3hP8QWDmFry1Gc7PUhgx
  summary:
    url: https://naveropenapi.apigw.ntruss.com/text-summary/v1/summarize
    clientId: ryaea7fblc
    clientSecret: geJm11Mo8RpgdtZobTqbM8tQk8B3LpBTkFEjzNYL
  tts:
    url: https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts
    clientId: bq5zklpfji
    clientSecret: o4ccdkYf8HjYqSnO0nKF4K5gCyhbppEH3ABxz1Lm