spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.215.149:3306/zooflix?serverTimezone=UTC&characterEncoding=UTF-8
    username: malangcow
    password: malang203
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379

server:
  port: 8089

jwt:
  secret: malangmalangmalangmalangmalangmalangcowcowcowcowzooflixmalangcowzoozooflextflextflixflixzooflixmalang

python:
  endpoint:
    news:
      crawling: http://127.0.0.1:8000//radio/crawling/translation/endpoint
      summary: http://127.0.0.1:8000/radio/summary/endpoint
      tts: http://127.0.0.1:8000/radio/tts/endpoint
  path:
    news: C:\projects\myapi\News.py
    end-price: C:\projects\myapi\EndPrice.py
  news:
    url: https://www.cnbc.com/world-markets/
  ppg:
    url: https://naveropenapi.apigw.ntruss.com/nmt/v1/translation
    clientId: qag4d44o5y
    clientSecret: eYaYbTl9z0UJ4lBqWrut3hP8QWDmFry1Gc7PUhgx
  summary:
    url: https://naveropenapi.apigw.ntruss.com/text-summary/v1/summarize
    clientId: ryaea7fblc
    clientSecret: geJm11Mo8RpgdtZobTqbM8tQk8B3LpBTkFEjzNYL
  tts:
    url: https://naveropenapi.apigw.ntruss.com/tts-premium/v1/tts
    clientId: bq5zklpfji
    clientSecret: o4ccdkYf8HjYqSnO0nKF4K5gCyhbppEH3ABxz1Lm