spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://13.124.215.149:3306/zooflix?serverTimezone=UTC&characterEncoding=UTF-8
    username: malangcow
    password: malang203
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

  jwt:
    secret: malangmalangmalangmalangmalangmalang

python:
  endpoint:
    news:
      crawling: http://127.0.0.1:8000/radio/crawling/endpoint
      summary: http://127.0.0.1:8000/radio/summary/endpoint
      tts: http://127.0.0.1:8000/radio/tts/endpoint
  path:
    news: C:\projects\myapi\News.py
    end-price: C:\projects\myapi\EndPrice.py
  news:
    url: https://news.naver.com/section/102
