spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.31.169:3305/zooflix?serverTimezone=UTC&characterEncoding=UTF-8
    username: malangcow
    password: malang203
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

  jwt:
    secret: malangmalangmalangmalangmalangmalang